language: php
php:
    - 7.0
    - 7.1
    - 7.2
install:
    - composer install --prefer-source --no-interaction
before_script:
    - phpenv rehash
script:
    - ./bin/phpstan.sh
    - ./vendor/bin/phpcs
